# Docker Compose configuration for Dapr Actor Demo
#
# This file provides two modes of operation:
# 1. Default mode: Runs only the actor service with Redis and Dapr sidecar
#    Usage: docker compose up -d
# 2. Client mode: Additionally runs the client application with its own Dapr sidecar
#    Usage: docker compose --profile client up -d
#
# The actor service builds from source code, so no pre-compilation is needed.
# All services use health checks to ensure proper startup ordering.

services:
  # Redis for state store
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Actor service (using local binary)
  actor-service:
    image: golang:1.24-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "3500:3500"
    environment:
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    depends_on:
      redis:
        condition: service_healthy
    command: |
      sh -c "
        apk add --no-cache ca-certificates git &&
        go mod download &&
        go run ./cmd/server
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Dapr sidecar for actor service  
  actor-service-dapr:
    image: daprio/daprd:1.14.4
    command: [
      "./daprd",
      "-app-id", "actor-service",
      "-app-port", "8080",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/config/config.yaml",
      "-log-level", "info"
    ]
    volumes:
      - "./configs/dapr:/components"
      - "./configs/dapr:/config"
    depends_on:
      actor-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: "service:actor-service"

  # Client application
  client:
    image: golang:1.24-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DAPR_HTTP_ENDPOINT=http://client-dapr:3501
    depends_on:
      - actor-service-dapr
    command: |
      sh -c "
        apk add --no-cache ca-certificates git &&
        go mod download &&
        go run ./cmd/client
      "
    profiles:
      - client

  # Dapr sidecar for client
  client-dapr:
    image: daprio/daprd:1.14.4
    command: [
      "./daprd",
      "-app-id", "client",
      "-dapr-http-port", "3501",
      "-dapr-grpc-port", "50002",
      "-log-level", "info"
    ]
    depends_on:
      - actor-service-dapr
    profiles:
      - client

networks:
  default:
    driver: bridge