services:
  # Redis for state store
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Actor service using pre-built binary
  actor-service:
    image: alpine:latest
    working_dir: /app
    volumes:
      - ./bin/server:/app/server:ro
    ports:
      - "8080:8080"
      - "3500:3500"
    depends_on:
      redis:
        condition: service_healthy
    command: ["/app/server"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Dapr sidecar for actor service  
  actor-service-dapr:
    image: daprio/daprd:1.14.4
    command: [
      "./daprd",
      "-app-id", "actor-service",
      "-app-port", "8080",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/config/config.yaml",
      "-log-level", "info"
    ]
    volumes:
      - "./configs/dapr:/components"
      - "./configs/dapr:/config"
    depends_on:
      actor-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: "service:actor-service"

networks:
  default:
    driver: bridge